package com.mycompany.ejemplo2;
// Generated Feb 8, 2019 11:07:34 PM by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int idmarcador;
     private String descripcion;
     private Integer lonitud;
     private Integer latitus;

    public Marcador() {
    }

	
    public Marcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public Marcador(int idmarcador, String descripcion, Integer lonitud, Integer latitus) {
       this.idmarcador = idmarcador;
       this.descripcion = descripcion;
       this.lonitud = lonitud;
       this.latitus = latitus;
    }
   
    public int getIdmarcador() {
        return this.idmarcador;
    }
    
    public void setIdmarcador(int idmarcador) {
        this.idmarcador = idmarcador;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getLonitud() {
        return this.lonitud;
    }
    
    public void setLonitud(Integer lonitud) {
        this.lonitud = lonitud;
    }
    public Integer getLatitus() {
        return this.latitus;
    }
    
    public void setLatitus(Integer latitus) {
        this.latitus = latitus;
    }




}


